package com.yuzhe.codeagent.enums;

public enum AgentEventType {
    SESSION_CREATED,
    USER_MESSAGE,
    ASSISTANT_MESSAGE,
    TOOL_CALL_STARTED,
    TOOL_CALL_FINISHED,
    TOOL_CALL_FAILED,
    PATCH_APPLY_STARTED,
    PATCH_APPLY_FINISHED,
    PATCH_APPLY_FAILED,
    COMMAND_STARTED,
    COMMAND_FINISHED,
    TEST_FAILED,
    TEST_PASSED,
    DIFF_GENERATED,
    GIT_BRANCH_CREATE_STARTED,
    GIT_BRANCH_CREATED,
    GIT_COMMIT_STARTED,
    GIT_COMMITTED,
    PR_DRAFT_GENERATED,
    GIT_WORKFLOW_FAILED,
    TASK_FINISHED,
    TASK_FAILED,
    CANCELLED,
    PARSE_ERROR,
    UNKNOWN
}
