CREATE TABLE IF NOT EXISTS agent_task (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_no VARCHAR(64) NOT NULL UNIQUE,
  repo_path VARCHAR(1024) NOT NULL,
  execution_mode VARCHAR(32) NOT NULL DEFAULT 'DOCKER',
  source_repo_path VARCHAR(1024),
  workspace_path VARCHAR(1024),
  sandbox_id BIGINT,
  user_goal CLOB NOT NULL,
  session_id VARCHAR(128),
  status VARCHAR(32) NOT NULL,
  max_steps INT NOT NULL,
  auto_approve BOOLEAN NOT NULL,
  use_real_model BOOLEAN NOT NULL,
  runner_pid BIGINT,
  started_at TIMESTAMP,
  finished_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  error_message CLOB,
  final_summary CLOB,
  final_diff CLOB
);

ALTER TABLE agent_task ADD COLUMN IF NOT EXISTS execution_mode VARCHAR(32) NOT NULL DEFAULT 'DOCKER';
ALTER TABLE agent_task ADD COLUMN IF NOT EXISTS source_repo_path VARCHAR(1024);
ALTER TABLE agent_task ADD COLUMN IF NOT EXISTS workspace_path VARCHAR(1024);
ALTER TABLE agent_task ADD COLUMN IF NOT EXISTS sandbox_id BIGINT;

CREATE TABLE IF NOT EXISTS agent_task_event (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL,
  session_id VARCHAR(128),
  event_type VARCHAR(64) NOT NULL,
  payload CLOB,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS agent_task_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL,
  stream_type VARCHAR(16) NOT NULL,
  content CLOB NOT NULL,
  created_at TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS agent_sandbox (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL,
  container_id VARCHAR(128),
  container_name VARCHAR(128) NOT NULL,
  image VARCHAR(256) NOT NULL,
  workspace_path VARCHAR(1024) NOT NULL,
  repo_workspace_path VARCHAR(1024) NOT NULL,
  status VARCHAR(32) NOT NULL,
  cpu_limit VARCHAR(32),
  memory_limit VARCHAR(32),
  network_enabled BOOLEAN NOT NULL,
  started_at TIMESTAMP,
  finished_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  error_message CLOB
);

CREATE TABLE IF NOT EXISTS agent_git_workflow (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT NOT NULL UNIQUE,
  repo_path VARCHAR(1024) NOT NULL,
  workspace_repo_path VARCHAR(1024),
  base_branch VARCHAR(256),
  work_branch VARCHAR(256),
  base_commit VARCHAR(64),
  commit_hash VARCHAR(64),
  commit_message VARCHAR(512),
  pr_title VARCHAR(512),
  pr_description CLOB,
  status VARCHAR(32) NOT NULL,
  created_at TIMESTAMP NOT NULL,
  updated_at TIMESTAMP NOT NULL,
  error_message CLOB
);
